name: Test & Build Main/Develop

on:
  push:
    branches:
      - main
      - develop
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    env:
      # Add your environment variables here, e.g. API_URL: ${{ secrets.API_URL }}
      # See .env.example for required variables (not found in repo)
    steps:
    - name: Print current branch
      run: git branch -a

    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '22.14.0'

    - name: Install dependencies
      run: npm ci

    - name: Run linter
      run: npm run lint

    - name: Run unit tests
      run: npm run test:unit

    - name: Run E2E tests
      run: npm run test:e2e

    - name: Build project
      run: npm run build

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-test
    env:
      # Add your environment variables here, e.g. API_URL: ${{ secrets.API_URL }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      run: |
        docker build -t your-dockerhub-username/your-app-name:latest .
        docker push your-dockerhub-username/your-app-name:latest

    - name: Deploy to DigitalOcean
      uses: digitalocean/action-doctl@v2
      with:
        token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      run: |
        doctl apps update your-app-id --spec .do/app.yaml 