name: Playwright Tests
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    env:
      SUPABASE_URL: ${{ secrets.E2E_URL }}
      SUPABASE_KEY: ${{ secrets.E2E_SUPABASE_KEY }}
      E2E_URL: "http://localhost:3000"
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 18
    - name: Install dependencies
      run: npm ci
    - name: Create .env.test file
      run: |
        echo "SUPABASE_URL=${{ secrets.E2E_URL }}" > .env.test
        echo "SUPABASE_KEY=${{ secrets.E2E_SUPABASE_KEY }}" >> .env.test
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps
    - name: Run Playwright tests
      run: npx playwright test
    - uses: actions/upload-artifact@v3
      if: always()
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30
